### ISSUE TITLE
Italic ascenders are different from Roman ascenders

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/Lora-Cyrillic#3]
Italic, MediumItalic and BoldItalic hhea.ascender and typoAscender are 1033 while Regular, Medium and Bold hhea.ascender and typoAscender are 1006.

Fontbakery gives the following fail:
🔥 FAIL: Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts.

Should the Italic ascenders match that of Roman styles?

I looked at the Lora fonts downloadable from Google Fonts and they also have Italics with these ascender values. Is Fontbakery getting a different version of the Italics, with the same values as Roman styles instead, for that error to occur?

/cc @m4rc1e

**Comment by m4rc1e** [comment]
> Should the Italic ascenders match that of Roman styles?

They are meant to match. However, since this is a popular family, I'm going to ignore it.
