### ISSUE TITLE
"Reserved Font Name" in OFL.txt and copyright string

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/Lora-Cyrillic#4]
Lora’s OFL.txt and the copyright strings have "Reserved Font Name".
Fontbakery gives a warning:
⚠ WARN: Name table strings must not contain the string 'Reserved Font Name'

Is this something that needs to change?
/cc @m4rc1e

**Comment by m4rc1e** [comment]
I think it's fine for this release. Let's just leave it as it is.
